{
  config,
  pkgs,
  clan-core,
  ...
}: {
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix

    ../../modules/synapse-admin.nix

    clan-core.clanModules.matrix-synapse
  ];
  # Put your username here for login
  users.users.user.name = "lk";

  # Set this for clan commands use ssh i.e. `clan machines update`
  # If you change the hostname, you need to update this line to root@<new-hostname>
  # This only works however if you have avahi running on your admin machine else use IP
  clan.core.networking.targetHost = "root@cloudy";

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      22
      80
      443
    ];
  };

  disko.devices.disk.main.device = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_59179759";

  users.users.root.openssh.authorizedKeys.keys = [
    ''
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJRat12+538VwG/IAv5R4AjdNYz/GATO7ULQnXtYC2HK lk@tower
    ''
  ];

  environment.systemPackages = with pkgs; [
    git
    vim
  ];

  clan.nginx.acme.email = "lennart@koziollek.com";
  clan.matrix-synapse = {
    app_domain = "matrix.echsen.club";
    server_tld = "echsen.club";
    users = {
      schromp = {
        name = "schromp";
        admin = true;
      };
    };
  };

  /*
  After jon is deployed, uncomment the following line
  This will allow sara to share the VPN overlay network with jon
  The networkId is generated by the first deployment of jon
  */
  # clan.core.networking.zerotier.networkId = builtins.readFile ../jon/facts/zerotier-network-id;
}
