{
  config,
  pkgs,
  clan-core,
  ...
}: {
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
    clan-core.clanModules.matrix-synapse
  ];
  # Put your username here for login
  users.users.user.name = "lk";

  # Set this for clan commands use ssh i.e. `clan machines update`
  # If you change the hostname, you need to update this line to root@<new-hostname>
  # This only works however if you have avahi running on your admin machine else use IP
  clan.core.networking.targetHost = "root@cloudy";

  disko.devices.disk.main.device = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_59179759";

  users.users.root.openssh.authorizedKeys.keys = [
    ''
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJRat12+538VwG/IAv5R4AjdNYz/GATO7ULQnXtYC2HK lk@tower
    ''
  ];

  environment.systemPackages = with pkgs; [
    git
    vim
  ];

  clan.nginx.acme.email = "lennart@koziollek.com";
  clan.matrix-synapse = {
    app_domain = "matrix.echsen.club";
    server_tld = "echsen.club";
    users = {
      schromp = {
        name = "schromp";
        admin = true;
      };
    };
  };

  clan.core.vars.generators.matrix-synapse-captcha = {
    prompts.captcha-private-key = {
      type = "line";
      description = "The private key for the captcha";
    };
    prompts.captcha-public-key = {
      type = "line";
      description = "The public key for the captcha";
    };

    files.captcha-config = {
      secret = true;
      owner = "matrix-synapse";
    };

    script = ''
      echo "enable_registration_captcha: true" > $out/captcha-config
      echo "recaptcha_public_key: $prompts/public-key" >> $out/captcha-config
      echo "recaptcha_private_key: $prompts/private-key" >> $out/captcha-config
    '';
  };

  services.matrix-synapse = {
    settings = {
      enable_registration = false;
      log = {
        root = {
          level = "DEBUG";
        };
      };
    };
    extraConfigFiles = [
      config.clan.core.vars.generators.matrix-synapse-captcha.files.captcha-config.path
    ];
  };

  /*
  After jon is deployed, uncomment the following line
  This will allow sara to share the VPN overlay network with jon
  The networkId is generated by the first deployment of jon
  */
  # clan.core.networking.zerotier.networkId = builtins.readFile ../jon/facts/zerotier-network-id;
}
